version: "3"
services:
  web:
    build: .
    ports:
      - "${PORT}:${PORT}"
  redis:
    image: redis
    container_name: "redis"
    volumes:
            - ./docker/redis.conf:/redis.conf
    ports:
      - 6379:6379
    command: [ "redis-server", "/redis.conf" ]
